apiVersion: apps/v1
kind: Deployment
metadata:
  name: gas-monitoring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gas-monitoring
  template:
    metadata:
      labels:
        app: gas-monitoring
    spec:
      containers:
        - name: gas-monitoring
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
