apiVersion: v1
kind: Service
metadata:
  name: gas-monitoring
spec:
  selector:
    app: gas-monitoring
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
